var skills = [
"Absolution", 
"Ancestral Protector", 
"Ancestral Warchief", 
"Animate Guardian", 
"Animate Weapon", 
"Arc", 
"Arcanist Brand", 
"Armageddon Brand", 
"Artillery Ballista", 
"Ball Lightning", 
"Bane", 
"Barrage", 
"Bear Trap", 
"Blade Blast", 
"Blade Flurry", 
"Blade Trap", 
"Blade Vortex", 
"Bladefall", 
"Bladestorm", 
"Blast Rain", 
"Blazing Salvo", 
"Blight", 
"Bodyswap", 
"Boneshatter", 
"Burning Arrow", 
"Caustic Arrow", 
"Chain Hook", 
"Charged Dash", 
"Cleave", 
"Cobra Lash", 
"Cold Snap", 
"Consecrated Path", 
"Contagion", 
"Convocation", 
"Corrupting Fever", 
"Crackling Lance", 
"Creeping Frost", 
"Cremation", 
"Cyclone", 
"Dark Pact", 
"Detonate Dead", 
"Discharge", 
"Divine Ire", 
"Dominating Blow", 
"Double Strike", 
"Dual Strike", 
"Earthquake", 
"Earthshatter", 
"Elemental Hit", 
"Essence Drain", 
"Ethereal Knives", 
"Explosive Arrow", 
"Explosive Concoction", 
"Explosive Trap", 
"Exsanguinate", 
"Eye of Winter", 
"Fire Trap", 
"Fireball", 
"Firestorm", 
"Flame Surge", 
"Flame Wall", 
"Flameblast", 
"Flamethrower Trap", 
"Flicker Strike", 
"Forbidden Rite", 
"Freezing Pulse", 
"Frenzy", 
"Frost Blades", 
"Frost Bomb", 
"Frost Shield", 
"Frostbolt", 
"Galvanic Arrow", 
"Glacial Cascade", 
"Glacial Hammer", 
"Ground Slam", 
"Heavy Strike", 
"Hexblast", 
"Holy Flame Totem", 
"Ice Crash", 
"Ice Nova", 
"Ice Shot", 
"Ice Spear", 
"Ice Trap", 
"Icicle Mine", 
"Immortal Call", 
"Incinerate", 
"Infernal Blow", 
"Kinetic Blast", 
"Kinetic Bolt", 
"Lacerate", 
"Lancing Steel", 
"Leap Slam", 
"Lightning Arrow", 
"Lightning Spire Trap", 
"Lightning Strike", 
"Lightning Tendrils", 
"Lightning Trap", 
"Lightning Warp", 
"Manabond", 
"Mirror Arrow", 
"Molten Strike", 
"Orb of Storms", 
"Penance Brand", 
"Perforate", 
"Pestilent Strike", 
"Poisonous Concoction", 
"Power Siphon", 
"Puncture", 
"Purifying Flame", 
"Pyroclast Mine", 
"Rage Vortex", 
"Rain of Arrows", 
"Raise Spectre", 
"Raise Zombie", 
"Reap", 
"Reave", 
"Reckoning", 
"Righteous Fire", 
"Riposte", 
"Rolling Magma", 
"Scorching Ray", 
"Scourge Arrow", 
"Searing Bond", 
"Seismic Trap", 
"Shattering Steel", 
"Shield Charge", 
"Shield Crush", 
"Shock Nova", 
"Shockwave Totem", 
"Shrapnel Ballista", 
"Siege Ballista", 
"Siphoning Trap", 
"Smite", 
"Smoke Mine", 
"Soulrend", 
"Spark", 
"Spectral Helix", 
"Spectral Shield Throw", 
"Spectral Throw", 
"Spellslinger", 
"Split Arrow", 
"Splitting Steel", 
"Static Strike", 
"Storm Brand", 
"Storm Burst", 
"Storm Call", 
"Storm Rain", 
"Stormbind", 
"Stormblast Mine", 
"Summon Chaos Golem", 
"Summon Flame Golem", 
"Summon Holy Relic", 
"Summon Ice Golem", 
"Summon Lightning Golem", 
"Summon Raging Spirit", 
"Summon Reaper", 
"Summon Skeletons", 
"Sunder", 
"Sweep", 
"Tectonic Slam", 
"Tornado", 
"Tornado Shot", 
"Toxic Rain", 
"Unearth", 
"Perforate", 
"Vengeance", 
"Venom Gyre", 
"Vigilant Strike", 
"Viper Strike", 
"Void Sphere", 
"Volatile Dead", 
"Voltaxic Burst", 
"Vortex", 
"Wave of Conviction", 
"Whirling Blades", 
"Wild Strike", 
"Winter Orb", 
"Wintertide Brand"
]
